version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: moonrocket
      POSTGRES_USER: moonrocketuser
      POSTGRES_PASSWORD: qwerty
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./api 
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://moonrocketuser:qwerty@db:5432/moonrocket
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000/api
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data: